apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
 name: getotp-demo-pipeline-binding
spec:
 params:
 - name: gitrevision
   value: $(body.head_commit.id)
 - name: gitrepositoryurl
   value: $(body.repository.html_url)
 - name: pull_request_title
   value: $(body.repository.full_name)