apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: getotp-demo-github-listener-interceptor
  name: getotp-demo-github-listener-el
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-getotp-demo-github-listener-interceptor