kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-workshop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-csi
  volumeMode: Filesystem