apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-rhacs-operator-ns.yaml
  - 02-operatorgroup.yaml
  - 03-acs-operator-sub.yaml
  - 011-operator-stackrox-ns.yaml
  - 04-central.yaml
  - 05-securecluster.yaml
  - 06-pipeline-sub.yaml