apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: getotp
spec:
  host: demo.apps.rosa-cnn2f.dts3.p1.openshiftapps.com
  path: /getotp
  port:
    targetPort: 8180
  to:
    kind: Service
    name: getotpservice
    weight: 100
