apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: getotp
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: getOtp
    repoURL: 'https://github.com/mohansidda/gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
