apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline
  namespace: openshift-gitops
spec:
  destination:
    namespace: cicd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: pipeline-deploy
    repoURL: 'https://github.com/mohansidda/gitops.git'
    targetRevision: HEAD
